### PR TITLE
D3 version bump

### LINKED ISSUE #44: Node dependency updates
These instructions don't necessarily need to end up in the README, but I do want to document a few things (if only for my own ability to recall how I fixed things) after wrestling with node for over an hour. 

1. Many of the packages currently here may need to be updated to their latest releases, including both minor and major releases. Several updates include: 

```
 autoprefixer                ^9.7.6  →  ^10.2.6     
 browser-sync               ^2.26.7  →  ^2.27.3     
 css-loader                  ^3.5.3  →   ^5.2.6     
 eslint                      ^6.8.0  →  ^7.29.0     
 eslint-config-airbnb-base  ^14.1.0  →  ^14.2.1     
 eslint-plugin-import       ^2.20.2  →  ^2.23.4     
 gulp                        ^4.0.0  →   ^4.0.2     
 gulp-load-plugins           ^2.0.3  →   ^2.0.7     
 gulp-postcss                ^8.0.0  →   ^9.0.0     
 gulp-sass                   ^4.0.1  →   ^5.0.0     
 style-loader                ^1.2.0  →   ^3.0.0     
 webpack                    ^4.43.0  →  ^5.41.0     
 webpack-cli                ^3.3.11  →   ^4.7.2     
 d3                         ^5.16.0  →   ^7.0.0     
 foundation-sites            ^6.6.2  →   ^6.6.3     
 jquery                      ^3.4.1  →   ^3.6.0     
 motion-ui                   ~2.0.0  →   ~2.0.3     
 what-input                  ^5.1.2  →  ^5.2.10 
```

2. We can check the above information using the [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) package. This is installed  globally by `npm -g npm-check-updates`. Then you can run `ncu -u` in the directory to implement updates to modules. **Note that this will make changes to `package.json`**.

3. Now you can run `npm install` to install new versions, and `npm audit` to look for fixes / `npm audit fix --force` to force fixes.

In my testing so far, the only thing these updates seem to break is the mouseover events on points on the Catholic diocese map: the pop-up no longer follows the mouse pointer, but this should be fairly easy fix (this *might* even be an issue with my own computer, I'm investigating.)

### PR DESCRIPTION
**Pull request by hepplerj**
This branch handles upgrading Node dependencies (see #44) and repairs D3 issues identified in #47. This fixes any issues with D3 v7 in the current visualizations.

I don't think we can quite close #44 yet with this -- I'm investigating how we can remove the reliance on `gulp` in favor of Hugo handling the scss bundling.

### CODE REVIEW

**Comment by hepplerj** [comment]
Actually, I might suggest we hold off on merging this into `master` until I figure out how to get Hugo to handle the `scss` compiling/bundling since I started that work in this branch also. Just so we're not making a bunch of unneccessary branches.

But, the D3 update here is ready for review and testing.

**Comment by hepplerj** [comment]
This branch also includes an update for #48 by setting `js.Build` to `es2020`.

**Comment by hepplerj** [comment]
The most recent push on **7/19/21** now includes SCSS and JS bundling, minifying, fingerprinting, and integrity all handled by Hugo and removes our dependency on `gulp`. After review, this should resolve everything in #44.

**Comment by lmullen** [comment]
This is amazing work, @hepplerj. Thanks so much.

**Pull request merged**
